/**
 * generate-icons.js
 * Creates SoundPilot app icons from an inline SVG design.
 *
 * Outputs:
 *   assets/icon.png   — 1024×1024  (Linux + source)
 *   assets/icon.ico   — multi-size Windows icon (16,24,32,48,64,128,256)
 *   assets/icon.icns  — macOS (generated by electron-builder on macOS CI runner)
 *
 * Run:  node scripts/generate-icons.js
 */

const sharp    = require('sharp')
const { imagesToIco } = require('png-to-ico')
const fs       = require('fs')
const path     = require('path')

const ASSETS = path.join(__dirname, '..', 'assets')
if (!fs.existsSync(ASSETS)) fs.mkdirSync(ASSETS, { recursive: true })

// ── SVG icon design ───────────────────────────────────────────────────────────
// Dark rounded-square background + 7 cyan frequency-spectrum bars
// + a pilot diamond crosshair mark at the center top
const SVG = `
<svg width="1024" height="1024" viewBox="0 0 1024 1024"
     xmlns="http://www.w3.org/2000/svg">
  <defs>
    <!-- Background gradient: near-black with a faint blue tint -->
    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1" gradientUnits="objectBoundingBox">
      <stop offset="0%"   stop-color="#0d1117"/>
      <stop offset="100%" stop-color="#080c12"/>
    </linearGradient>

    <!-- Bar gradient: bright cyan top → deeper teal bottom -->
    <linearGradient id="barGrad" x1="0" y1="0" x2="0" y2="1" gradientUnits="objectBoundingBox">
      <stop offset="0%"   stop-color="#22d3ee"/>
      <stop offset="100%" stop-color="#0e7490"/>
    </linearGradient>

    <!-- Soft glow around bars -->
    <filter id="glow" x="-30%" y="-15%" width="160%" height="130%">
      <feGaussianBlur in="SourceGraphic" stdDeviation="14" result="blur"/>
      <feMerge>
        <feMergeNode in="blur"/>
        <feMergeNode in="SourceGraphic"/>
      </feMerge>
    </filter>

    <!-- Rounded-square clip -->
    <clipPath id="roundClip">
      <rect width="1024" height="1024" rx="190" ry="190"/>
    </clipPath>
  </defs>

  <!-- Background -->
  <rect width="1024" height="1024" rx="190" fill="url(#bg)"/>

  <!-- Subtle horizontal centre line -->
  <line x1="80" y1="560" x2="944" y2="560"
        stroke="#22d3ee" stroke-width="1.5" opacity="0.12"/>

  <!-- ── Frequency bars ──────────────────────────────────────────────────────
       7 bars, each 80 px wide, 36 px gap
       Total = 7×80 + 6×36 = 560 + 216 = 776 px
       Start X = (1024 − 776) / 2 = 124
       Baseline (bottom of bars) at y = 600
       Heights (tallest in centre, symmetric):  160 280 400 500 400 280 160
  -->
  <g filter="url(#glow)" clip-path="url(#roundClip)">
    <!-- Bar 1  x=124  h=160 -->
    <rect x="124" y="440" width="80" height="160" rx="10" fill="url(#barGrad)" opacity="0.55"/>
    <!-- Bar 2  x=240  h=280 -->
    <rect x="240" y="320" width="80" height="280" rx="10" fill="url(#barGrad)" opacity="0.70"/>
    <!-- Bar 3  x=356  h=400 -->
    <rect x="356" y="200" width="80" height="400" rx="10" fill="url(#barGrad)" opacity="0.85"/>
    <!-- Bar 4 (centre)  x=472  h=500 -->
    <rect x="472" y="100" width="80" height="500" rx="10" fill="url(#barGrad)" opacity="1.00"/>
    <!-- Bar 5  x=588  h=400 -->
    <rect x="588" y="200" width="80" height="400" rx="10" fill="url(#barGrad)" opacity="0.85"/>
    <!-- Bar 6  x=704  h=280 -->
    <rect x="704" y="320" width="80" height="280" rx="10" fill="url(#barGrad)" opacity="0.70"/>
    <!-- Bar 7  x=820  h=160 -->
    <rect x="820" y="440" width="80" height="160" rx="10" fill="url(#barGrad)" opacity="0.55"/>
  </g>

  <!-- ── Pilot diamond crosshair (brand mark) ────────────────────────────────
       Centred at (512, 780) — below the bars, in the lower third
  -->
  <g transform="translate(512,790)" filter="url(#glow)">
    <!-- Outer diamond -->
    <polygon points="0,-38  38,0  0,38  -38,0"
             fill="none" stroke="#22d3ee" stroke-width="5" opacity="0.9"/>
    <!-- Inner filled diamond -->
    <polygon points="0,-18  18,0  0,18  -18,0"
             fill="#22d3ee" opacity="0.95"/>
    <!-- Crosshair arms -->
    <line x1="-62" y1="0" x2="-44" y2="0" stroke="#22d3ee" stroke-width="3" opacity="0.6"/>
    <line x1="44"  y1="0" x2="62"  y2="0" stroke="#22d3ee" stroke-width="3" opacity="0.6"/>
    <line x1="0" y1="-62" x2="0" y2="-44" stroke="#22d3ee" stroke-width="3" opacity="0.6"/>
    <line x1="0" y1="44"  x2="0" y2="62"  stroke="#22d3ee" stroke-width="3" opacity="0.6"/>
  </g>

  <!-- Bottom accent line -->
  <rect x="362" y="880" width="300" height="4" rx="2" fill="#22d3ee" opacity="0.35"/>
</svg>
`

async function main() {
  console.log('🎨  Generating SoundPilot icons…')

  // ── 1. 1024×1024 PNG ────────────────────────────────────────────────────────
  const pngPath = path.join(ASSETS, 'icon.png')
  await sharp(Buffer.from(SVG))
    .resize(1024, 1024)
    .png()
    .toFile(pngPath)
  console.log('  ✓  assets/icon.png  (1024×1024)')

  // ── 2. Windows .ico — pass raw RGBA objects that imagesToIco expects ────────
  const sizes = [16, 24, 32, 48, 64, 128, 256]
  const imgObjs = await Promise.all(
    sizes.map(async s => {
      const { data } = await sharp(Buffer.from(SVG))
        .resize(s, s)
        .ensureAlpha()
        .raw()
        .toBuffer({ resolveWithObject: true })
      return { data, width: s, height: s }
    })
  )

  const icoBuf = await imagesToIco(imgObjs)
  const icoPath = path.join(ASSETS, 'icon.ico')
  fs.writeFileSync(icoPath, icoBuf)
  console.log('  ✓  assets/icon.ico  (16/24/32/48/64/128/256)')

  // ── 3. 512×512 PNG for macOS (electron-builder uses iconutil on macOS CI) ──
  const mac512Path = path.join(ASSETS, 'icon-mac.png')
  await sharp(Buffer.from(SVG)).resize(512, 512).png().toFile(mac512Path)
  console.log('  ✓  assets/icon-mac.png  (512×512, used by CI for .icns)')

  console.log('\n✅  Done — icons written to assets/')
}

main().catch(err => { console.error(err); process.exit(1) })
